다층퍼셉트론 = 단층퍼셉트론을 여러 층으로 쌓아 올려 만든 신경망\
입력층과 출력층, 한개 이상의 은닉층으로 구성

In [2]:
#MLPClassifier
# learning_rate_init : 학습률 초기값.(기본값 0.001)
# max_iter : 학습의 반복 횟수(에폭) (기본값 200)
# activation : 은닉층에서 적용할 활성화 함수 이름.
# hidden_layer_sizes : 은닉층의 규모에 대한 튜플. 기본값 (100,) = 1개의 은닉층 있고 100개의 노드 배치

In [3]:
import numpy as np

In [4]:
import sklearn.datasets as d

In [5]:
mnist = d.fetch_openml('mnist_784',version=1)
X = mnist.data
y = mnist.target

In [6]:
import sklearn.model_selection as ms
X_train, X_test, y_train, y_test = ms.train_test_split(X,y,test_size=0.3,random_state=1)

In [7]:
import sklearn.neural_network as nn
#MLPClassifier : 다중분류시 사용
pnn_clf = nn.MLPClassifier(learning_rate_init=0.001,max_iter = 1000, activation = 'relu',
                hidden_layer_sizes=(10,10))
clf =pnn_clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [8]:
#분석 결과 평가(정확도)
import sklearn.metrics as mt
print('정확도 : ',mt.accuracy_score(y_test, y_pred))
print(mt.confusion_matrix(y_test,y_pred))

정확도 :  0.9108095238095238
[[1989    0   18    8   13    3    6    9   28    2]
 [   1 2260   42    8    2    0    0   11   64    2]
 [  18   11 1947   10   21    5   14   39   55    4]
 [  13   18  108 1839    2   75    2   33   38   37]
 [   5    4   19    1 1855    3   17   14   14  131]
 [  32   14    4   72   19 1620   42    3   69   48]
 [  32    2   18    0   26   25 1856    0   40    0]
 [  10   17   16   10   23    1    2 2009    4   64]
 [  18   22   53   26   10   23   16    5 1851   24]
 [   4    9    3   18   32   18    1   49   21 1901]]
